FROM node:16-alpine

RUN apk add chromium

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 80

ARG MAILCHIMP_API_KEY
ENV MAILCHIMP_API_KEY $MAILCHIMP_API_KEY

ARG MONGODB_URI
ENV MONGODB_URI $MONGODB_URI

ARG DEBUG
ENV DEBUG $DEBUG

ARG SENDGRID_API_KEY
ENV SENDGRID_API_KEY $SENDGRID_API_KEY

ARG SESSION_SECRET
ENV SESSION_SECRET $SESSION_SECRET

ARG VIMEO_CLIENT_ID
ENV VIMEO_CLIENT_ID $VIMEO_CLIENT_ID

ARG VIMEO_SECRET
ENV VIMEO_SECRET $VIMEO_SECRET

ARG VIMEO_ACCESS_TOKEN
ENV VIMEO_ACCESS_TOKEN $VIMEO_ACCESS_TOKEN

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY $OPENAI_API_KEY

ARG APIFY_TOKEN
ENV APIFY_TOKEN $APIFY_TOKEN

ARG NODE_ENV
ENV NODE_ENV production

CMD [ "npm", "run", "start"]